lines = []
lines.append('/**')
lines.append(' * Packive Bleed Guide System v8')
lines.append(' * - Uses getBoundingRect() for each green cut-line path')
lines.append(' * - Collects actual canvas-coordinate endpoints from bounding rects')
lines.append(' * - Chains line segments and applies Clipper.js offset')
lines.append(' */')
lines.append('')
lines.append('const DEFAULT_BLEED_MM = 3;')
lines.append('')
lines.append('interface BleedConfig {')
lines.append('  scale: number;')
lines.append('  bleedMm?: number;')
lines.append('}')
lines.append('')
lines.append('function extractCutSegments(canvas: any): [number, number][][] | null {')
lines.append('  const g = canvas.getObjects().find((o: any) =>')
lines.append('    o._isDieLine || o._isDieline || o._isGuideLayer ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (!g) { console.warn("[BLEED] No dieline group"); return null; }')
lines.append('')
lines.append('  const children = g._objects || [];')
lines.append('  const greenPaths = children.filter((ch: any) =>')
lines.append('    ch.type === "path" && ch.stroke && ch.stroke.includes("0,166,80")')
lines.append('  );')
lines.append('  if (greenPaths.length === 0) { console.warn("[BLEED] No green paths"); return null; }')
lines.append('')
lines.append('  // Use getBoundingRect for each path to get canvas coordinates')
lines.append('  // Each green path is a straight line (M x1,y1 L x2,y2)')
lines.append('  // getBoundingRect gives us the exact canvas position')
lines.append('  const segments: [number, number][][] = [];')
lines.append('')
lines.append('  greenPaths.forEach((p: any) => {')
lines.append('    const br = p.getBoundingRect();')
lines.append('    // Determine if vertical or horizontal line')
lines.append('    if (br.width < 2) {')
lines.append('      // Vertical line')
lines.append('      const x = br.left + br.width / 2;')
lines.append('      segments.push([[x, br.top], [x, br.top + br.height]]);')
lines.append('    } else if (br.height < 2) {')
lines.append('      // Horizontal line')
lines.append('      const y = br.top + br.height / 2;')
lines.append('      segments.push([[br.left, y], [br.left + br.width, y]]);')
lines.append('    } else {')
lines.append('      // Diagonal or other - use corners')
lines.append('      segments.push([[br.left, br.top], [br.left + br.width, br.top + br.height]]);')
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append('  console.log("[BLEED] Extracted " + segments.length + " segments via getBoundingRect");')
lines.append('  return segments;')
lines.append('}')
lines.append('')
lines.append('function buildOutlineFromSegments(segments: [number, number][][]): [number, number][] {')
lines.append('  // Collect all unique endpoints')
lines.append('  const allPts: [number, number][] = [];')
lines.append('  segments.forEach(seg => seg.forEach(pt => allPts.push(pt)));')
lines.append('')
lines.append('  // Find bounding extents')
lines.append('  const xs = allPts.map(p => p[0]);')
lines.append('  const ys = allPts.map(p => p[1]);')
lines.append('  const minX = Math.min(...xs);')
lines.append('  const maxX = Math.max(...xs);')
lines.append('  const minY = Math.min(...ys);')
lines.append('  const maxY = Math.max(...ys);')
lines.append('')
lines.append('  // Separate vertical and horizontal segments')
lines.append('  const verticals: { x: number; y1: number; y2: number }[] = [];')
lines.append('  const horizontals: { y: number; x1: number; x2: number }[] = [];')
lines.append('')
lines.append('  segments.forEach(seg => {')
lines.append('    const dx = Math.abs(seg[1][0] - seg[0][0]);')
lines.append('    const dy = Math.abs(seg[1][1] - seg[0][1]);')
lines.append('    if (dx < 2) {')
lines.append('      verticals.push({ x: (seg[0][0] + seg[1][0]) / 2, y1: Math.min(seg[0][1], seg[1][1]), y2: Math.max(seg[0][1], seg[1][1]) });')
lines.append('    } else {')
lines.append('      horizontals.push({ y: (seg[0][1] + seg[1][1]) / 2, x1: Math.min(seg[0][0], seg[1][0]), x2: Math.max(seg[0][0], seg[1][0]) });')
lines.append('    }')
lines.append('  });')
lines.append('')
lines.append('  // Sort verticals by x, horizontals by y')
lines.append('  verticals.sort((a, b) => a.x - b.x);')
lines.append('  horizontals.sort((a, b) => a.y - b.y);')
lines.append('')
lines.append('  console.log("[BLEED] Verticals:", verticals.length, "Horizontals:", horizontals.length);')
lines.append('')
lines.append('  // Find the outermost vertical (leftmost and rightmost)')
lines.append('  // and outermost horizontals (topmost and bottommost)')
lines.append('  // Then build the outline by walking the boundary')
lines.append('')
lines.append('  // Strategy: collect all cut-line intersection points')
lines.append('  // For packaging dielines, the outline is formed by the outermost segments')
lines.append('  // Use a point-walking approach on the boundary')
lines.append('')
lines.append('  // Collect boundary points: endpoints of all segments')
lines.append('  const boundaryPts: [number, number][] = [];')
lines.append('')
lines.append('  // Add vertical line endpoints')
lines.append('  verticals.forEach(v => {')
lines.append('    boundaryPts.push([v.x, v.y1]);')
lines.append('    boundaryPts.push([v.x, v.y2]);')
lines.append('  });')
lines.append('')
lines.append('  // Add horizontal line endpoints')
lines.append('  horizontals.forEach(h => {')
lines.append('    boundaryPts.push([h.x1, h.y]);')
lines.append('    boundaryPts.push([h.x2, h.y]);')
lines.append('  });')
lines.append('')
lines.append('  // Remove duplicates (within tolerance)')
lines.append('  const TOL = 3;')
lines.append('  const unique: [number, number][] = [];')
lines.append('  boundaryPts.forEach(pt => {')
lines.append('    const exists = unique.some(u => Math.abs(u[0] - pt[0]) < TOL && Math.abs(u[1] - pt[1]) < TOL);')
lines.append('    if (!exists) unique.push(pt);')
lines.append('  });')
lines.append('')
lines.append('  console.log("[BLEED] Unique boundary points:", unique.length);')
lines.append('')
lines.append('  // Sort points to form a clockwise outline')
lines.append('  // Compute centroid')
lines.append('  const cx = unique.reduce((s, p) => s + p[0], 0) / unique.length;')
lines.append('  const cy = unique.reduce((s, p) => s + p[1], 0) / unique.length;')
lines.append('')
lines.append('  // Sort by angle from centroid')
lines.append('  unique.sort((a, b) => {')
lines.append('    const angA = Math.atan2(a[1] - cy, a[0] - cx);')
lines.append('    const angB = Math.atan2(b[1] - cy, b[0] - cx);')
lines.append('    return angA - angB;')
lines.append('  });')
lines.append('')
lines.append('  console.log("[BLEED] Sorted outline: " + unique.length + " points");')
lines.append('  return unique;')
lines.append('}')
lines.append('')
lines.append('async function clipperOffset(polygon: [number, number][], offsetPx: number): Promise<[number, number][]> {')
lines.append('  try {')
lines.append('    const ClipperLib = (await import("js-clipper")).default || await import("js-clipper");')
lines.append('    const SCALE = 100;')
lines.append('    const path = polygon.map(([x, y]) => ({ X: Math.round(x * SCALE), Y: Math.round(y * SCALE) }));')
lines.append('    const co = new ClipperLib.ClipperOffset();')
lines.append('    co.AddPath(path, ClipperLib.JoinType.jtMiter, ClipperLib.EndType.etClosedPolygon);')
lines.append('    const solution: any[] = [];')
lines.append('    co.Execute(solution, offsetPx * SCALE);')
lines.append('    if (solution.length > 0 && solution[0].length > 0) {')
lines.append('      const result = solution[0].map((pt: any) => [pt.X / SCALE, pt.Y / SCALE] as [number, number]);')
lines.append('      console.log("[BLEED] Clipper: " + polygon.length + " -> " + result.length + " pts, offset=" + offsetPx.toFixed(1) + "px");')
lines.append('      return result;')
lines.append('    }')
lines.append('  } catch (e) {')
lines.append('    console.warn("[BLEED] Clipper failed:", e);')
lines.append('  }')
lines.append('  return polygon;')
lines.append('}')
lines.append('')
lines.append('function polygonToPathData(pts: [number, number][]): string {')
lines.append('  if (pts.length < 3) return "";')
lines.append('  return pts.map((p, i) => (i === 0 ? "M" : "L") + " " + p[0].toFixed(2) + " " + p[1].toFixed(2)).join(" ") + " Z";')
lines.append('}')
lines.append('')
lines.append('function getDielineBBox(canvas: any) {')
lines.append('  const objs = canvas.getObjects().filter((o: any) =>')
lines.append('    o._isDieLine || o._isDieline ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (objs.length === 0) return null;')
lines.append('  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;')
lines.append('  objs.forEach((o: any) => {')
lines.append('    const b = o.getBoundingRect();')
lines.append('    minX = Math.min(minX, b.left); minY = Math.min(minY, b.top);')
lines.append('    maxX = Math.max(maxX, b.left + b.width); maxY = Math.max(maxY, b.top + b.height);')
lines.append('  });')
lines.append('  return { left: minX, top: minY, width: maxX - minX, height: maxY - minY };')
lines.append('}')
lines.append('')
lines.append('export async function addBleedGuides(canvas: any, config: BleedConfig) {')
lines.append('  const { Path, Rect } = await import("fabric");')
lines.append('  const bleedMm = config.bleedMm ?? DEFAULT_BLEED_MM;')
lines.append('  removeBleedGuides(canvas);')
lines.append('')
lines.append('  const segments = extractCutSegments(canvas);')
lines.append('  if (segments && segments.length >= 3) {')
lines.append('    const outline = buildOutlineFromSegments(segments);')
lines.append('    if (outline.length >= 3) {')
lines.append('      const bleedPx = bleedMm * config.scale;')
lines.append('      const offsetPoly = await clipperOffset(outline, bleedPx);')
lines.append('      if (offsetPoly.length >= 3) {')
lines.append('        const pathData = polygonToPathData(offsetPoly);')
lines.append('        const bleedPath = new Path(pathData, {')
lines.append('          fill: "transparent",')
lines.append('          stroke: "#22c55e",')
lines.append('          strokeWidth: 1.2,')
lines.append('          strokeDashArray: [8, 4],')
lines.append('          selectable: false,')
lines.append('          evented: false,')
lines.append('          excludeFromExport: true,')
lines.append('          name: "__bleed_guide__",')
lines.append('          _isBleedGuide: true,')
lines.append('        });')
lines.append('        canvas.add(bleedPath);')
lines.append('        canvas.requestRenderAll();')
lines.append('        console.log("[BLEED] Path bleed guide: " + bleedMm + "mm, " + offsetPoly.length + " vertices");')
lines.append('        return bleedPath;')
lines.append('      }')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  // Fallback')
lines.append('  console.log("[BLEED] Falling back to bbox rect");')
lines.append('  const bbox = getDielineBBox(canvas);')
lines.append('  if (!bbox) { console.warn("[BLEED] No dieline"); return null; }')
lines.append('  const bleedPx = bleedMm * config.scale;')
lines.append('  const bleedRect = new Rect({')
lines.append('    left: bbox.left - bleedPx,')
lines.append('    top: bbox.top - bleedPx,')
lines.append('    width: bbox.width + bleedPx * 2,')
lines.append('    height: bbox.height + bleedPx * 2,')
lines.append('    fill: "transparent",')
lines.append('    stroke: "#22c55e",')
lines.append('    strokeWidth: 1.2,')
lines.append('    strokeDashArray: [8, 4],')
lines.append('    selectable: false,')
lines.append('    evented: false,')
lines.append('    excludeFromExport: true,')
lines.append('    name: "__bleed_guide__",')
lines.append('    _isBleedGuide: true,')
lines.append('  });')
lines.append('  canvas.add(bleedRect);')
lines.append('  canvas.requestRenderAll();')
lines.append('  console.log("[BLEED] Bbox fallback: " + bleedMm + "mm (" + bleedPx.toFixed(1) + "px)");')
lines.append('  return bleedRect;')
lines.append('}')
lines.append('')
lines.append('export function removeBleedGuides(canvas: any) {')
lines.append('  const guides = canvas.getObjects().filter(')
lines.append('    (o: any) => o._isBleedGuide || o.name === "__bleed_guide__"')
lines.append('  );')
lines.append('  guides.forEach((g: any) => canvas.remove(g));')
lines.append('  if (guides.length > 0) canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function toggleBleedGuides(canvas: any, visible: boolean) {')
lines.append('  canvas.getObjects().forEach((o: any) => {')
lines.append('    if (o._isBleedGuide || o.name === "__bleed_guide__") {')
lines.append('      o.visible = visible;')
lines.append('    }')
lines.append('  });')
lines.append('  canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function calcPdfBoxes(')
lines.append('  canvasWidth: number,')
lines.append('  canvasHeight: number,')
lines.append('  bleedMm: number = DEFAULT_BLEED_MM')
lines.append(') {')
lines.append('  const bleedPt = bleedMm * 2.83465;')
lines.append('  return {')
lines.append('    trimBox: [0, 0, canvasWidth, canvasHeight],')
lines.append('    bleedBox: [-bleedPt, -bleedPt, canvasWidth + bleedPt, canvasHeight + bleedPt],')
lines.append('    artBox: [bleedPt, bleedPt, canvasWidth - bleedPt, canvasHeight - bleedPt],')
lines.append('  };')
lines.append('}')

content = '\n'.join(lines)
with open('src/lib/bleed-guide.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"bleed-guide.ts v8: {len(content)} bytes")
