# Write bleed-guide.ts v7 with clean encoding
lines = []
lines.append('/**')
lines.append(' * Packive Bleed Guide System v7')
lines.append(' * - Uses calcTransformMatrix for accurate coordinate transform')
lines.append(' * - Chains cut-line segments into closed polygon')
lines.append(' * - Clipper.js offset for concave/convex shapes')
lines.append(' */')
lines.append('')
lines.append('const DEFAULT_BLEED_MM = 3;')
lines.append('')
lines.append('interface BleedConfig {')
lines.append('  scale: number;')
lines.append('  bleedMm?: number;')
lines.append('}')
lines.append('')
lines.append('function extractCutSegments(canvas: any) {')
lines.append('  const g = canvas.getObjects().find((o: any) =>')
lines.append('    o._isDieLine || o._isDieline || o._isGuideLayer ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (!g) { console.warn("[BLEED] No dieline group"); return null; }')
lines.append('')
lines.append('  const children = g._objects || [];')
lines.append('  const greenPaths = children.filter((ch: any) =>')
lines.append('    ch.type === "path" && ch.stroke && ch.stroke.includes("0,166,80")')
lines.append('  );')
lines.append('  if (greenPaths.length === 0) { console.warn("[BLEED] No green paths"); return null; }')
lines.append('')
lines.append('  const segments: [number, number][][] = [];')
lines.append('  greenPaths.forEach((p: any) => {')
lines.append('    if (!p.path || p.path.length < 2) return;')
lines.append('    let matrix: number[];')
lines.append('    try { matrix = p.calcTransformMatrix(); }')
lines.append('    catch(e) { matrix = [1,0,0,1,0,0]; }')
lines.append('    const pts: [number, number][] = [];')
lines.append('    p.path.forEach((cmd: any[]) => {')
lines.append('      let x: number, y: number;')
lines.append('      if (cmd[0] === "M" || cmd[0] === "L") { x = cmd[1]; y = cmd[2]; }')
lines.append('      else if (cmd[0] === "C") { x = cmd[5]; y = cmd[6]; }')
lines.append('      else return;')
lines.append('      const cx = matrix[0] * x + matrix[2] * y + matrix[4];')
lines.append('      const cy = matrix[1] * x + matrix[3] * y + matrix[5];')
lines.append('      pts.push([cx, cy]);')
lines.append('    });')
lines.append('    if (pts.length >= 2) segments.push(pts);')
lines.append('  });')
lines.append('')
lines.append('  console.log("[BLEED] Extracted " + segments.length + " cut-line segments");')
lines.append('  return segments;')
lines.append('}')
lines.append('')
lines.append('function buildOutlinePolygon(segments: [number, number][][]): [number, number][] {')
lines.append('  if (segments.length === 0) return [];')
lines.append('  const TOLERANCE = 5.0;')
lines.append('  const used = new Array(segments.length).fill(false);')
lines.append('  const chain: [number, number][] = [];')
lines.append('')
lines.append('  let startIdx = 0;')
lines.append('  let leftmost = Infinity;')
lines.append('  segments.forEach((seg, i) => {')
lines.append('    const sx = Math.min(seg[0][0], seg[seg.length-1][0]);')
lines.append('    if (sx < leftmost) { leftmost = sx; startIdx = i; }')
lines.append('  });')
lines.append('')
lines.append('  used[startIdx] = true;')
lines.append('  chain.push(...segments[startIdx]);')
lines.append('  let current = chain[chain.length - 1];')
lines.append('')
lines.append('  for (let iter = 0; iter < segments.length * 2; iter++) {')
lines.append('    let bestIdx = -1, bestDist = Infinity, bestReverse = false;')
lines.append('    for (let i = 0; i < segments.length; i++) {')
lines.append('      if (used[i]) continue;')
lines.append('      const seg = segments[i];')
lines.append('      const d1 = Math.hypot(current[0] - seg[0][0], current[1] - seg[0][1]);')
lines.append('      const d2 = Math.hypot(current[0] - seg[seg.length-1][0], current[1] - seg[seg.length-1][1]);')
lines.append('      if (d1 < bestDist) { bestDist = d1; bestIdx = i; bestReverse = false; }')
lines.append('      if (d2 < bestDist) { bestDist = d2; bestIdx = i; bestReverse = true; }')
lines.append('    }')
lines.append('    if (bestIdx === -1 || bestDist > TOLERANCE * 50) break;')
lines.append('    used[bestIdx] = true;')
lines.append('    const seg = bestReverse ? [...segments[bestIdx]].reverse() : segments[bestIdx];')
lines.append('    const skip = Math.hypot(current[0] - seg[0][0], current[1] - seg[0][1]) < TOLERANCE;')
lines.append('    chain.push(...(skip ? seg.slice(1) : seg));')
lines.append('    current = chain[chain.length - 1];')
lines.append('  }')
lines.append('')
lines.append('  console.log("[BLEED] Outline: " + chain.length + " pts from " + used.filter(Boolean).length + "/" + segments.length + " segs");')
lines.append('  return chain;')
lines.append('}')
lines.append('')
lines.append('async function clipperOffset(polygon: [number, number][], offsetPx: number): Promise<[number, number][]> {')
lines.append('  try {')
lines.append('    const ClipperLib = (await import("js-clipper")).default || await import("js-clipper");')
lines.append('    const SCALE = 1000;')
lines.append('    const path = polygon.map(([x, y]) => ({ X: Math.round(x * SCALE), Y: Math.round(y * SCALE) }));')
lines.append('    const co = new ClipperLib.ClipperOffset();')
lines.append('    co.AddPath(path, ClipperLib.JoinType.jtMiter, ClipperLib.EndType.etClosedPolygon);')
lines.append('    const solution: any[] = [];')
lines.append('    co.Execute(solution, offsetPx * SCALE);')
lines.append('    if (solution.length > 0 && solution[0].length > 0) {')
lines.append('      const result = solution[0].map((pt: any) => [pt.X / SCALE, pt.Y / SCALE] as [number, number]);')
lines.append('      console.log("[BLEED] Clipper offset: " + polygon.length + " -> " + result.length + " pts");')
lines.append('      return result;')
lines.append('    }')
lines.append('  } catch (e) {')
lines.append('    console.warn("[BLEED] Clipper failed:", e);')
lines.append('  }')
lines.append('  return simpleOffset(polygon, offsetPx);')
lines.append('}')
lines.append('')
lines.append('function simpleOffset(polygon: [number, number][], offsetPx: number): [number, number][] {')
lines.append('  if (polygon.length < 3) return polygon;')
lines.append('  const cx = polygon.reduce((s, p) => s + p[0], 0) / polygon.length;')
lines.append('  const cy = polygon.reduce((s, p) => s + p[1], 0) / polygon.length;')
lines.append('  return polygon.map(([x, y]) => {')
lines.append('    const dx = x - cx; const dy = y - cy;')
lines.append('    const dist = Math.sqrt(dx * dx + dy * dy) || 1;')
lines.append('    return [x + (dx / dist) * offsetPx, y + (dy / dist) * offsetPx] as [number, number];')
lines.append('  });')
lines.append('}')
lines.append('')
lines.append('function polygonToPathData(pts: [number, number][]): string {')
lines.append('  if (pts.length < 3) return "";')
lines.append('  return pts.map((p, i) => (i === 0 ? "M" : "L") + " " + p[0].toFixed(2) + " " + p[1].toFixed(2)).join(" ") + " Z";')
lines.append('}')
lines.append('')
lines.append('function getDielineBBox(canvas: any) {')
lines.append('  const objs = canvas.getObjects().filter((o: any) =>')
lines.append('    o._isDieLine || o._isDieline ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (objs.length === 0) return null;')
lines.append('  let minX = Infinity, minY = Infinity, maxX = -Infinity, maxY = -Infinity;')
lines.append('  objs.forEach((o: any) => {')
lines.append('    const b = o.getBoundingRect();')
lines.append('    minX = Math.min(minX, b.left); minY = Math.min(minY, b.top);')
lines.append('    maxX = Math.max(maxX, b.left + b.width); maxY = Math.max(maxY, b.top + b.height);')
lines.append('  });')
lines.append('  return { left: minX, top: minY, width: maxX - minX, height: maxY - minY };')
lines.append('}')
lines.append('')
lines.append('export async function addBleedGuides(canvas: any, config: BleedConfig) {')
lines.append('  const { Path, Rect } = await import("fabric");')
lines.append('  const bleedMm = config.bleedMm ?? DEFAULT_BLEED_MM;')
lines.append('  removeBleedGuides(canvas);')
lines.append('')
lines.append('  const segments = extractCutSegments(canvas);')
lines.append('  if (segments && segments.length >= 3) {')
lines.append('    const outline = buildOutlinePolygon(segments);')
lines.append('    if (outline.length >= 3) {')
lines.append('      const bleedPx = bleedMm * config.scale;')
lines.append('      const offsetPoly = await clipperOffset(outline, bleedPx);')
lines.append('      if (offsetPoly.length >= 3) {')
lines.append('        const pathData = polygonToPathData(offsetPoly);')
lines.append('        const bleedPath = new Path(pathData, {')
lines.append('          fill: "transparent",')
lines.append('          stroke: "#22c55e",')
lines.append('          strokeWidth: 1.2,')
lines.append('          strokeDashArray: [8, 4],')
lines.append('          selectable: false,')
lines.append('          evented: false,')
lines.append('          excludeFromExport: true,')
lines.append('          name: "__bleed_guide__",')
lines.append('          _isBleedGuide: true,')
lines.append('        });')
lines.append('        canvas.add(bleedPath);')
lines.append('        canvas.requestRenderAll();')
lines.append('        console.log("[BLEED] Offset bleed guide added: " + bleedMm + "mm, " + offsetPoly.length + " vertices");')
lines.append('        return bleedPath;')
lines.append('      }')
lines.append('    }')
lines.append('  }')
lines.append('')
lines.append('  console.log("[BLEED] Falling back to bbox rect");')
lines.append('  const bbox = getDielineBBox(canvas);')
lines.append('  if (!bbox) { console.warn("[BLEED] No dieline for bleed"); return null; }')
lines.append('  const bleedPx = bleedMm * config.scale;')
lines.append('  const bleedRect = new Rect({')
lines.append('    left: bbox.left - bleedPx,')
lines.append('    top: bbox.top - bleedPx,')
lines.append('    width: bbox.width + bleedPx * 2,')
lines.append('    height: bbox.height + bleedPx * 2,')
lines.append('    fill: "transparent",')
lines.append('    stroke: "#22c55e",')
lines.append('    strokeWidth: 1.2,')
lines.append('    strokeDashArray: [8, 4],')
lines.append('    selectable: false,')
lines.append('    evented: false,')
lines.append('    excludeFromExport: true,')
lines.append('    name: "__bleed_guide__",')
lines.append('    _isBleedGuide: true,')
lines.append('  });')
lines.append('  canvas.add(bleedRect);')
lines.append('  canvas.requestRenderAll();')
lines.append('  console.log("[BLEED] Bbox fallback: " + bleedMm + "mm (" + bleedPx.toFixed(1) + "px)");')
lines.append('  return bleedRect;')
lines.append('}')
lines.append('')
lines.append('export function removeBleedGuides(canvas: any) {')
lines.append('  const guides = canvas.getObjects().filter(')
lines.append('    (o: any) => o._isBleedGuide || o.name === "__bleed_guide__"')
lines.append('  );')
lines.append('  guides.forEach((g: any) => canvas.remove(g));')
lines.append('  if (guides.length > 0) canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function toggleBleedGuides(canvas: any, visible: boolean) {')
lines.append('  canvas.getObjects().forEach((o: any) => {')
lines.append('    if (o._isBleedGuide || o.name === "__bleed_guide__") {')
lines.append('      o.visible = visible;')
lines.append('    }')
lines.append('  });')
lines.append('  canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function calcPdfBoxes(')
lines.append('  canvasWidth: number,')
lines.append('  canvasHeight: number,')
lines.append('  bleedMm: number = DEFAULT_BLEED_MM')
lines.append(') {')
lines.append('  const bleedPt = bleedMm * 2.83465;')
lines.append('  return {')
lines.append('    trimBox: [0, 0, canvasWidth, canvasHeight],')
lines.append('    bleedBox: [-bleedPt, -bleedPt, canvasWidth + bleedPt, canvasHeight + bleedPt],')
lines.append('    artBox: [bleedPt, bleedPt, canvasWidth - bleedPt, canvasHeight - bleedPt],')
lines.append('  };')
lines.append('}')

content = '\n'.join(lines)
with open('src/lib/bleed-guide.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"bleed-guide.ts v7 written cleanly: {len(content)} bytes")
