lines = []
lines.append('/**')
lines.append(' * Packive Bleed Guide System v12')
lines.append(' * - Creates bleed rect matching dieline group transform exactly')
lines.append(' * - Same position, scale, origin as dieline group + bleed offset')
lines.append(' */')
lines.append('')
lines.append('const DEFAULT_BLEED_MM = 3;')
lines.append('')
lines.append('interface BleedConfig {')
lines.append('  scale?: number;')
lines.append('  bleedMm?: number;')
lines.append('  svgMmW?: number;')
lines.append('}')
lines.append('')
lines.append('export async function addBleedGuides(canvas: any, config: BleedConfig) {')
lines.append('  const { Rect } = await import("fabric");')
lines.append('  const bleedMm = config.bleedMm ?? DEFAULT_BLEED_MM;')
lines.append('  removeBleedGuides(canvas);')
lines.append('')
lines.append('  const g = canvas.getObjects().find((o: any) =>')
lines.append('    o._isDieLine || o._isDieline || o._isGuideLayer ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (!g) { console.warn("[BLEED] No dieline found"); return null; }')
lines.append('')
lines.append('  // Bleed in SVG units (same coordinate system as group width/height)')
lines.append('  const svgMmW = config.svgMmW || g.width * 0.264583;')
lines.append('  const svgUnitsPerMm = g.width / svgMmW;')
lines.append('  const bleedSvgUnits = bleedMm * svgUnitsPerMm;')
lines.append('')
lines.append('  // Create rect in same coordinate system as group')
lines.append('  // Group has originX/Y = center, so we match that')
lines.append('  const bleedRect = new Rect({')
lines.append('    left: g.left,')
lines.append('    top: g.top,')
lines.append('    originX: "center",')
lines.append('    originY: "center",')
lines.append('    width: g.width + bleedSvgUnits * 2,')
lines.append('    height: g.height + bleedSvgUnits * 2,')
lines.append('    scaleX: g.scaleX,')
lines.append('    scaleY: g.scaleY,')
lines.append('    angle: g.angle || 0,')
lines.append('    fill: "transparent",')
lines.append('    stroke: "#ff3333",')
lines.append('    strokeWidth: 1 / g.scaleX,')
lines.append('    strokeDashArray: [],')
lines.append('    selectable: false,')
lines.append('    evented: false,')
lines.append('    excludeFromExport: true,')
lines.append('    name: "__bleed_guide__",')
lines.append('    _isBleedGuide: true,')
lines.append('  });')
lines.append('')
lines.append('  canvas.add(bleedRect);')
lines.append('  canvas.requestRenderAll();')
lines.append('  const bleedPx = bleedSvgUnits * g.scaleX;')
lines.append('  console.log("[BLEED] Guide added: " + bleedMm + "mm = " + bleedPx.toFixed(1) + "px, svgUnits=" + bleedSvgUnits.toFixed(1));')
lines.append('  return bleedRect;')
lines.append('}')
lines.append('')
lines.append('export function removeBleedGuides(canvas: any) {')
lines.append('  const guides = canvas.getObjects().filter(')
lines.append('    (o: any) => o._isBleedGuide || o.name === "__bleed_guide__"')
lines.append('  );')
lines.append('  guides.forEach((g: any) => canvas.remove(g));')
lines.append('  if (guides.length > 0) canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function toggleBleedGuides(canvas: any, visible: boolean) {')
lines.append('  canvas.getObjects().forEach((o: any) => {')
lines.append('    if (o._isBleedGuide || o.name === "__bleed_guide__") {')
lines.append('      o.visible = visible;')
lines.append('    }')
lines.append('  });')
lines.append('  canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function calcPdfBoxes(')
lines.append('  canvasWidth: number,')
lines.append('  canvasHeight: number,')
lines.append('  bleedMm: number = DEFAULT_BLEED_MM')
lines.append(') {')
lines.append('  const bleedPt = bleedMm * 2.83465;')
lines.append('  return {')
lines.append('    trimBox: [0, 0, canvasWidth, canvasHeight],')
lines.append('    bleedBox: [-bleedPt, -bleedPt, canvasWidth + bleedPt, canvasHeight + bleedPt],')
lines.append('    artBox: [bleedPt, bleedPt, canvasWidth - bleedPt, canvasHeight - bleedPt],')
lines.append('  };')
lines.append('}')

content = '\n'.join(lines)
with open('src/lib/bleed-guide.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"bleed-guide.ts v12: {len(content)} bytes")
