lines = []
lines.append('/**')
lines.append(' * Packive Bleed Guide System v9')
lines.append(' * - Clean bounding-box bleed using dieline group getBoundingRect()')
lines.append(' * - Reliable, accurate, works with all dieline shapes')
lines.append(' * - Phase 2: path-following bleed for complex shapes')
lines.append(' */')
lines.append('')
lines.append('const DEFAULT_BLEED_MM = 3;')
lines.append('')
lines.append('interface BleedConfig {')
lines.append('  scale: number;')
lines.append('  bleedMm?: number;')
lines.append('}')
lines.append('')
lines.append('export async function addBleedGuides(canvas: any, config: BleedConfig) {')
lines.append('  const { Rect } = await import("fabric");')
lines.append('  const bleedMm = config.bleedMm ?? DEFAULT_BLEED_MM;')
lines.append('  removeBleedGuides(canvas);')
lines.append('')
lines.append('  // Find dieline group')
lines.append('  const g = canvas.getObjects().find((o: any) =>')
lines.append('    o._isDieLine || o._isDieline || o._isGuideLayer ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (!g) { console.warn("[BLEED] No dieline found"); return null; }')
lines.append('')
lines.append('  // Get accurate bounding rect in canvas coordinates')
lines.append('  const bbox = g.getBoundingRect();')
lines.append('  const bleedPx = bleedMm * config.scale;')
lines.append('')
lines.append('  const bleedRect = new Rect({')
lines.append('    left: bbox.left - bleedPx,')
lines.append('    top: bbox.top - bleedPx,')
lines.append('    width: bbox.width + bleedPx * 2,')
lines.append('    height: bbox.height + bleedPx * 2,')
lines.append('    fill: "transparent",')
lines.append('    stroke: "#22c55e",')
lines.append('    strokeWidth: 1,')
lines.append('    strokeDashArray: [6, 3],')
lines.append('    selectable: false,')
lines.append('    evented: false,')
lines.append('    excludeFromExport: true,')
lines.append('    name: "__bleed_guide__",')
lines.append('    _isBleedGuide: true,')
lines.append('  });')
lines.append('')
lines.append('  canvas.add(bleedRect);')
lines.append('  canvas.requestRenderAll();')
lines.append('  console.log("[BLEED] Guide added: " + bleedMm + "mm (" + bleedPx.toFixed(1) + "px) outside dieline bbox");')
lines.append('  return bleedRect;')
lines.append('}')
lines.append('')
lines.append('export function removeBleedGuides(canvas: any) {')
lines.append('  const guides = canvas.getObjects().filter(')
lines.append('    (o: any) => o._isBleedGuide || o.name === "__bleed_guide__"')
lines.append('  );')
lines.append('  guides.forEach((g: any) => canvas.remove(g));')
lines.append('  if (guides.length > 0) canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function toggleBleedGuides(canvas: any, visible: boolean) {')
lines.append('  canvas.getObjects().forEach((o: any) => {')
lines.append('    if (o._isBleedGuide || o.name === "__bleed_guide__") {')
lines.append('      o.visible = visible;')
lines.append('    }')
lines.append('  });')
lines.append('  canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function calcPdfBoxes(')
lines.append('  canvasWidth: number,')
lines.append('  canvasHeight: number,')
lines.append('  bleedMm: number = DEFAULT_BLEED_MM')
lines.append(') {')
lines.append('  const bleedPt = bleedMm * 2.83465;')
lines.append('  return {')
lines.append('    trimBox: [0, 0, canvasWidth, canvasHeight],')
lines.append('    bleedBox: [-bleedPt, -bleedPt, canvasWidth + bleedPt, canvasHeight + bleedPt],')
lines.append('    artBox: [bleedPt, bleedPt, canvasWidth - bleedPt, canvasHeight - bleedPt],')
lines.append('  };')
lines.append('}')

content = '\n'.join(lines)
with open('src/lib/bleed-guide.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"bleed-guide.ts v9 (clean bbox): {len(content)} bytes")
