lines = []
lines.append('/**')
lines.append(' * Packive Bleed Guide System v11')
lines.append(' * - Uses group position/scale directly (zoom-independent)')
lines.append(' * - No getBoundingRect (affected by viewport transform)')
lines.append(' */')
lines.append('')
lines.append('const DEFAULT_BLEED_MM = 3;')
lines.append('')
lines.append('interface BleedConfig {')
lines.append('  scale?: number;')
lines.append('  bleedMm?: number;')
lines.append('}')
lines.append('')
lines.append('export async function addBleedGuides(canvas: any, config: BleedConfig) {')
lines.append('  const { Rect } = await import("fabric");')
lines.append('  const bleedMm = config.bleedMm ?? DEFAULT_BLEED_MM;')
lines.append('  removeBleedGuides(canvas);')
lines.append('')
lines.append('  const g = canvas.getObjects().find((o: any) =>')
lines.append('    o._isDieLine || o._isDieline || o._isGuideLayer ||')
lines.append('    (o.name && (o.name.includes("dieline") || o.name.includes("__dieline")))')
lines.append('  );')
lines.append('  if (!g) { console.warn("[BLEED] No dieline found"); return null; }')
lines.append('')
lines.append('  // Calculate dieline bounds in object coordinates (zoom-independent)')
lines.append('  // Group center is at (g.left, g.top)')
lines.append('  // Rendered size = g.width * g.scaleX, g.height * g.scaleY')
lines.append('  const gScaleX = g.scaleX || 1;')
lines.append('  const gScaleY = g.scaleY || 1;')
lines.append('  const renderedW = g.width * gScaleX;')
lines.append('  const renderedH = g.height * gScaleY;')
lines.append('')
lines.append('  // Group origin is center by default in Fabric.js')
lines.append('  const dieLeft = g.left - renderedW / 2;')
lines.append('  const dieTop = g.top - renderedH / 2;')
lines.append('')
lines.append('  // Calculate bleed in object pixels')
lines.append('  // pxPerMm = renderedW / actualMmWidth')
lines.append('  // We know viewBox to mm conversion: svgMm = viewBox * 0.264583')
lines.append('  // renderedW = g.width * gScaleX where g.width is in SVG units')
lines.append('  // So pxPerMm = renderedW / (g.width * 0.264583)')
lines.append('  const svgMm = g.width * 0.264583;')
lines.append('  const pxPerMm = renderedW / svgMm;')
lines.append('  const bleedPx = bleedMm * pxPerMm;')
lines.append('')
lines.append('  const bleedRect = new Rect({')
lines.append('    left: dieLeft - bleedPx,')
lines.append('    top: dieTop - bleedPx,')
lines.append('    width: renderedW + bleedPx * 2,')
lines.append('    height: renderedH + bleedPx * 2,')
lines.append('    fill: "transparent",')
lines.append('    stroke: "#ff3333",')
lines.append('    strokeWidth: 1,')
lines.append('    strokeDashArray: [],')
lines.append('    selectable: false,')
lines.append('    evented: false,')
lines.append('    excludeFromExport: true,')
lines.append('    name: "__bleed_guide__",')
lines.append('    _isBleedGuide: true,')
lines.append('  });')
lines.append('')
lines.append('  canvas.add(bleedRect);')
lines.append('  canvas.requestRenderAll();')
lines.append('  console.log("[BLEED] Guide added: " + bleedMm + "mm = " + bleedPx.toFixed(1) + "px (pxPerMm=" + pxPerMm.toFixed(4) + ")");')
lines.append('  console.log("[BLEED] Dieline: left=" + dieLeft.toFixed(1) + " top=" + dieTop.toFixed(1) + " w=" + renderedW.toFixed(1) + " h=" + renderedH.toFixed(1));')
lines.append('  return bleedRect;')
lines.append('}')
lines.append('')
lines.append('export function removeBleedGuides(canvas: any) {')
lines.append('  const guides = canvas.getObjects().filter(')
lines.append('    (o: any) => o._isBleedGuide || o.name === "__bleed_guide__"')
lines.append('  );')
lines.append('  guides.forEach((g: any) => canvas.remove(g));')
lines.append('  if (guides.length > 0) canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function toggleBleedGuides(canvas: any, visible: boolean) {')
lines.append('  canvas.getObjects().forEach((o: any) => {')
lines.append('    if (o._isBleedGuide || o.name === "__bleed_guide__") {')
lines.append('      o.visible = visible;')
lines.append('    }')
lines.append('  });')
lines.append('  canvas.requestRenderAll();')
lines.append('}')
lines.append('')
lines.append('export function calcPdfBoxes(')
lines.append('  canvasWidth: number,')
lines.append('  canvasHeight: number,')
lines.append('  bleedMm: number = DEFAULT_BLEED_MM')
lines.append(') {')
lines.append('  const bleedPt = bleedMm * 2.83465;')
lines.append('  return {')
lines.append('    trimBox: [0, 0, canvasWidth, canvasHeight],')
lines.append('    bleedBox: [-bleedPt, -bleedPt, canvasWidth + bleedPt, canvasHeight + bleedPt],')
lines.append('    artBox: [bleedPt, bleedPt, canvasWidth - bleedPt, canvasHeight - bleedPt],')
lines.append('  };')
lines.append('}')

content = '\n'.join(lines)
with open('src/lib/bleed-guide.ts', 'w', encoding='utf-8', newline='\n') as f:
    f.write(content)
print(f"bleed-guide.ts v11: {len(content)} bytes")
